### ISSUE TITLE
Mechs can't repair apparel, weapon and staff

### ISSUE THREAD

**Issue by OldRomeo** [SuperPyroManiac/Rimworld-TieredMechs#10]
Hello, noticed that tiered mechs can't repair anything wih this [mod](https://steamcommunity.com/sharedfiles/filedetails/?id=733997423). They just take what require repair, repair kit, then stands in front of workbench (without adding HP to what they try to repair), then take repair kit of the table, take what they want to repair, place it again and loop this

**Comment by SuperPyroManiac** [comment]
Mod has not been updated in a while, and the comments all say that it's broken. I think it's an issue with that mod, not mine.

**Comment by OldRomeo** [comment]
You're right, some comments stating that the mode is not working exist, but it is due to lack reading skills of commentators. They skip the part where mod maker explain that you need to craft repair kit before you can repair anything. I'm not pushing and don't want to say anything bad about your mod, you're good mod maker and I highly appreciate your effort!

**Comment by SuperPyroManiac** [comment]
Oh ok, do you know if the vanilla bots work with this mod?

**Comment by OldRomeo** [comment]
Oh, sorry, I started my mechanitor career with your mod and built only cool mechs. Now, when I tried on clen save file with only two mods and spawned vanilla fabricator I see that there is issue even with vanilla. Sorry for disturbance

Exception in JobDriver tick for pawn Mech_Fabricor43688 driver=JobDriver_RepairItem (toilIndex=11) driver.job=(RepairItem (Job_6406) A=Thing_ElectricTableRepair43534 B=Thing_Apparel_CollarShirt1179 C=(124, 0, 129))
System.NullReferenceException: Object reference not set to an instance of an object
  at Repair.JobDriver_RepairItem+<>c__DisplayClass4_0.<MakeNewToils>b__1 () [0x0003f] in <3f4ea5fd60ac4e39bc78b2eca3f6412e>:0 
  at Verse.AI.JobDriver.DriverTick () [0x00163] in <1a99832471b046408678c845f00d13b6>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by SuperPyroManiac** [comment]
No problem, sorry I couldn't help.
