### ISSUE TITLE
Suggestion: Better Paramedic/Doctor Bot

### ISSUE THREAD

**Issue by TheOtherSmithal** [SuperPyroManiac/Rimworld-TieredMechs#2]
Would it be possible to have a better yet more expensive paramedic? I often use transhumanist idealogy with my mech lords, and augmenting a solo mechlord with implants is not possible with the paramedic's base 10 doctoring skill.

**Comment by SuperPyroManiac** [comment]
It's actually complete on my local build. I just need to test it when I get off work and I'll push it here and on steam. Level 20 with increased speed, but will have a high cost due to it being a perfect doctor. 

After that I plan to look into upgrading the militor.
