### ISSUE TITLE
Incompatibility with [FSF] Complex Jobs

### ISSUE THREAD

**Issue by Greylord-Daemos** [SuperPyroManiac/Rimworld-TieredMechs#4]
The jobs changed by this mod don't carry over like they do on the standard tier of mechanoids making them of very limited functionality.

https://steamcommunity.com/sharedfiles/filedetails/?id=2069684319

**Comment by SuperPyroManiac** [comment]
It's an issue on their end. Jobs on my mechs are assigned the same way as vanilla. He had posted that it's a known issue when adding on existing saves.
