### ISSUE TITLE
Tiered Paramedic not performing surgeries.

### ISSUE THREAD

**Issue by aandroxus1** [SuperPyroManiac/Rimworld-TieredMechs#8]

**Comment by aandroxus1** [comment]
Sorry for the false ticket, a mod conflict is causing the paramedic to not perform any operations.

**Comment by aandroxus1** [comment]
If it is helpful to you at all, the mod conflict is QualitySurgeon.

**Comment by SuperPyroManiac** [comment]
Can confirm, issue is on their side. Nothing I can really do.
